apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: SECRET_ENTITY
              valueFrom:
                secretKeyRef:
                  name: test-secret-staging
                  key: entity
