---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/benjaminBoboul/fluxcd-gitops-example

