apiVersion: v1
kind: Secret
metadata:
    name: test-secret
data:
    username: ENC[AES256_GCM,data:V0BCDUkAAdA=,iv:VHImKg7+1rL45feSEqvxX0uvD3lh8p9QFepnZLZqKEk=,tag:CqA5SG3TXIfXYtj1RZEvAw==,type:str]
    password: ENC[AES256_GCM,data:8i481khcXSbrpHy72NOWSQ==,iv:sAC7xJ6f+rhU7sDlcLZ9UqjnOPo8fnC8zBXBQRoXvcs=,tag:Krc8xYHg6+hOL2McxqbYIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-30T09:30:31Z'
    mac: ENC[AES256_GCM,data:d+N/TeMnWpC4mFZ7lNkNjOh5tqaWdELQ6l9Bc2MW+U8zY7rvGx1LkesZIIGUSbMZKRj2nAAZ2KxDswR/KrU4QM8qbtTLqlUZyKIpvLvEXDDxwxmXB0tFATnkhoZNtCmM3VjRA5hOTCg1kZsCSqdaiMo1wCHzPnQd6CpZa9VHrhQ=,iv:7sUNucPX73AgTtCUUp8HZe3Up8D6dStyl5Tg+3NTrLM=,tag:2IxmlM/b4tSeNy5D0ucywA==,type:str]
    pgp:
    -   created_at: '2021-03-30T09:30:29Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4FYqiHSGAvLARAAmdHNASW9EKzevEFyYp5sY3wQGuPBQJlclGtnW3ARf6Wc
            zfHZ5t0IXOrkbvT1mtHm6ZF8+Y9feQPmKOu7GmJga3bdFG3/uXXAu9cLUNdeGXaj
            lOF4gD1E3fluXsIwepQXjDhae/6yK6yp+1EpqqmdcUnu4SWtanztUwGCBJbhhK7g
            Eed0rxFfYwFdshOgDHhFYpskxgS5FWUZ310jdcWzLZyNkxzA5DRpUma56zLlO+j3
            INaX51S8RQsNofKGRVqj07QFkaszSaxjAd1OgOtlzKiWM470Q+rXsbWbRgNwBoU6
            vU8NczPrlB7pJXKGn/oilVKqCB6i9zsw2mzDRR+jgrOfAT/ebUVzBcie7tli2vy4
            rMfgY5BGlAPD0NuW3cCR3ovX8Jfd6zzIFOtwrCYjVq397Vf8XTMx+0Ii/gUqzfA1
            ME1zKl5hRG4PFi+hANqkscj+vD9ijYHgQKUL3im1C7WVNGM+2ioKsdhEDK54y6os
            DorQH/NhudFo1ebsNxwhbj5G+67qRgdP2K8OA9rbDojvjXqNacr91HdzpJiqY6iz
            ABruCFr9YP4g3mZPdHoHKPaIqHgDnkzWTggCuy/MgcGJp6FbgAQ3vDZsOyoUaeC2
            pDsyIkbBBTa2yd6cpiS0QvY6wm1vGCLghDhbXNgyxw2A0s/LcQnqfKdZgmoBAlvS
            XAFKdqRC6w1RQk1fg8nBvnbul5zQC4vn8f1vTLo4Ud9MF4sgZzsdkTXAXEhRt717
            3BrqXD286e1HycuSVRW6HjqBbOC0N61gAD7wAMD6FDQyl8V8WDLBt1zbHw3y
            =C72a
            -----END PGP MESSAGE-----
        fp: 15C70D3984A287D51BEAB5788F7AEE0BCFC19635
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
