apiVersion: v1
kind: Secret
metadata:
    name: test-secret
data:
    username: ENC[AES256_GCM,data:8LgB8kPKPJ0=,iv:QQpN92gpAG3MaeKU3st3kj/KF6xtQhNARnAg48Y0NRM=,tag:72ReNpSRZg+svw3zuKeOyA==,type:str]
    password: ENC[AES256_GCM,data:FACTgAtcIGIfhh30+mfd3A==,iv:VPHhRmcrkzlEPyIuIIvS/vxOYu1H/Cltl9xYe1EYxMc=,tag:OYZ2akc8IzfpHSej1tvL5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-29T18:29:46Z'
    mac: ENC[AES256_GCM,data:vX3gk35QIPL/0CNpYOnn8BkORuY6JU/fx4GzCIgQzjIx/7N7fk1oiaLm1nyYrg+Ewxzm6xuOP5kyzeb8Z71eeFPCn104/HG2dtXaHRB2I1eDLq5jj0PCVTNOxm/zTC9UQ4w3vOfN0oQmPYQL6XnNayLkRscsP4BkLOO3vlGQ3Rc=,iv:gVGgZv+fwz/tc36fSOMpZGFHgfj9nGkl+hEmmrPBbHc=,tag:ai4Y9Q++TAHXqSL5VNy2Ug==,type:str]
    pgp:
    -   created_at: '2021-03-29T18:29:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4FYqiHSGAvLAQ/7BOik1ebU8NWcgRLp84jQoA/ZXlZf/w7oeNSsby0Cgfee
            kpLaDTOukjEEVQ2fprDkffim2l5CYLCSiKn3POZd2+gITLQwc4Md8isDphqtUoOd
            fUQhzl01hiQCvP39Tii2rE9ICaev436PdKQSk6LY/1vj6S8goWG0eyygxKRfjCyM
            coJhHORkncoNibgd1F2XpLOtJUGh2vnVNngjGfoiULuLyqxvDtv3uFA9zn7Tfjdn
            7hvo2YZ76vieSEf58CpTR6QQBkarMGwQJb9Zj9TbtkxoqzElXxmDptlCyEfo9VCf
            0NkPD+9bMsIQLGCd0ZxymupJAZx2gv0gAHVX3nXu+G1a6Q9mdgOb5vxRpcpG8PvL
            wE1i4uJr1P0FFF9rMy/dxPtA8QzP6gB7RnBRtB+CeHClyvaUjCwoPE5mNRVU3AbF
            zmv60s2G9IkeOcQjY/pvNfHhP+LfeQdiP7cPJY4sC22DuuR54A4WJc70Yw7zDN31
            +/MLd7Xagbr3J2V5bDZzzHIvbeVAMXzR0/TheBIZOXN3BbO3yEgStE8w0YiL/K1m
            LC3BcFr5dgnB9mTMGY6BuO9aHrDyCdfTt1Hz0X3lHznZ/PS9QUoXGA/87vlih+BN
            HHq4/refJw0KasVd+eN1NCoy3Ae04oaOrJaZRgkkx3kd7nNoJVg5RxyNA5ivklTS
            XgFvGP1p4a/JjGl9KRwsTlAsUj3K4CCSXM0cuAd1QJYGf2gfygKQiwmw8+flY7+Y
            4gNuwfm5qbmww8T31D/TKuT9cj9hf7Zkrp2/uVhty9Bd89OL4b7ST8Il9lZKkkk=
            =LuUc
            -----END PGP MESSAGE-----
        fp: 15C70D3984A287D51BEAB5788F7AEE0BCFC19635
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
